version: '3'

networks:
  proxy_network:
    external:
      name: ${PROXY_NETWORK:-proxy_network}

volumes:
  certs:
    external:
      name: ${PROXY_CERTS_PATH:-./certs}
  conf:
    external:
      name: ${PROXY_CONFIG_PATH:-./conf.d}
  vhosts:
    external:
      name: ${PROXY_VHOSTS_PATH:-./vhosts.d}
  html:
    external:
      name: ${PROXY_HTML_PATH:-./html}

services:

  proxy_server:
    image: jwilder/nginx-proxy:alpine
    container_name: ${PROXY_SERVER_NAME:-proxy_server}
    hostname: ${PROXY_SERVER_NAME:-proxy_server}
    restart:
      unless-stopped
    networks:
      - proxy_network
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${PROXY_IP:-0.0.0.0}:80:80"
      - "${PROXY_IP:-0.0.0.0}:443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    logging:
      options:
        max-size: ${PROXY_SERVER_LOG_MAX_SIZE:-4m}
        max-file: ${PROXY_SERVER_LOG_MAX_FILE:-10}

  proxy_cert_mgr:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${PROXY_CERT_MGR_NAME:-proxy_cert_mgr}
    hostname: ${PROXY_CERT_MGR_NAME:-proxy_cert_mgr}
    restart:
      unless-stopped
    depends_on:
      - proxy_server
    networks:
      - proxy_network
    volumes:
      - certs:/etc/nginx/certs
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: ${PROXY_CERT_MGR_LOG_MAX_SIZE:-2m}
        max-file: ${PROXY_CERT_MGR_LOG_MAX_FILE:-10}
